name: Upload a new version of the NuGet package

on:
 push:
   tags:
     - 'v-*.*.*'

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Package and Publish NuGet
     run: |
       $env:VERSION_NAME = $env:REF_NAME.Substring(2)
       echo "Packing and publishing version: $env:VERSION_NAME"
       cd Trilobot\src
       dotnet pack -p:PackageVersion="$env:VERSION_NAME"
       dotnet nuget push ".\bin\Release\Trilobot.$env:VERSION_NAME".nupkg --api-key "$env:NUGETKEY" --source "https://api.nuget.org/v3/index.json"
     shell: pwsh
     env:
       NUGETKEY: ${{ secrets.NUGETKEY }}
       REF_NAME: ${{ github.ref_name }}
