name: Upload a new version of the NuGet package

on:
 push:
   tags:
     - 'v-*.*.*'

jobs:
 build:
   runs-on: windows-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Execute shell commands
     run: |
       $env:VERSION_NAME = $env:REF_NAME.Substring(2)
       echo $env:VERSION_NAME
     shell: pwsh
     env:
       NUGETKEY: ${{ secrets.NUGETKEY }}
       REF_NAME: ${{ github.ref_name }}
